services:
  authentication:
    container_name: authentication
    build:
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
    name: backend