# Generated by Django 5.0.7 on 2024-07-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_numebr',
            new_name='phone_number',
        ),
    ]
